C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 0 -e 8027
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 8027 -e 16054
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 16054 -e 24081
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 24081 -e 32108
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 32108 -e 40135
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 40135 -e 48162
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 48162 -e 56189
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 56189 -e 64216
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 64216 -e 72243
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 72243 -e 80270
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 80270 -e 88297
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 88297 -e 96324
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 96324 -e 104351
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 104351 -e 112378
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 112378 -e 120405
C:\Anaconda\envs\geo\python.exe "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\db\biomass\update_amazon_biomass_consumer.py" -s 120405 -e 120418
