SET python_exe=C:\Anaconda\envs\geo\python.exe
SET script="E:\heitor.guerra\PycharmProjects\pyLiDARForest\stuff\procScriptMultithread.py"

::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_1.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_2.bat"
%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_3.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_4.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_5.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_6.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_7.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_8.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_9.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_10.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_11.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_12.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_13.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_14.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_15.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_16.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_17.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_18.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_19.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_20.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_21.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_22.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_23.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_24.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_25.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_26.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_27.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_28.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_29.bat"
::%python_exe% %script% -c "12" -v "1" "E:\heitor.guerra\PycharmProjects\pyLiDARForest\app\builder\exe\palsar_tiles\palsar_30.bat"
